version: '3.4'

services:
  rockylinux-xfce4-xrdp:
    image: rockylinux-xfce4-xrdp:9
    hostname: rockylinux-xfce4-xrdp
    shm_size: '1gb'
    build:
      context: .
      dockerfile: ./Dockerfile
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    ports:
      - "3389:3389"
