version: '3.4'

services:
  rocky-xfce4-xrdp:
    image: rocky-xfce4-xrdp:latest
    hostname: rocky-xfce4-xrdp
    shm_size: '1gb'
    build:
      context: .
      dockerfile: ./Dockerfile
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    ports:
      - "3389:3389"
