version: '3.4'

services:
  rockylinux-xfce4-xrdp:
    image: darrick1/rockylinux-xfce4-xrdp:7
    hostname: rockylinux-xfce4-xrdp
    shm_size: '1gb'
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    ports:
      - "3389:3389"
